import type { Case, Task, AIAlert, Document, Message, TimeEntry, CaseEvent, DashboardStats } from '@/types';

export const mockUser = {
  id: 'user-1',
  email: 'sarah.chen@lexfirm.com',
  name: 'Sarah Chen',
  role: 'lawyer' as const,
  firm_id: 'firm-1',
  language: 'en' as const,
  avatar_url: undefined,
  created_at: '2024-01-15T09:00:00Z',
};

export const mockStats: DashboardStats = {
  total_cases: 24,
  active_cases: 18,
  high_risk_cases: 3,
  pending_messages: 7,
  pending_tasks: 12,
  alerts_today: 4,
};

export const mockCases: Case[] = [
  {
    id: 'case-1',
    firm_id: 'firm-1',
    title: 'Harrison v. Meridian Corp.',
    practice_area: 'Civil Litigation',
    status: 'in_court',
    risk_score: 78,
    risk_category: 'missed_deadline',
    budget: 1500000,
    billing_model: 'hourly',
    created_at: '2024-01-10T09:00:00Z',
    updated_at: '2024-03-18T14:30:00Z',
    client_name: 'James Harrison',
    lawyer_name: 'Sarah Chen',
    last_activity: '2024-03-18T14:30:00Z',
  },
  {
    id: 'case-2',
    firm_id: 'firm-1',
    title: 'Al-Rashid Family Trust',
    practice_area: 'Estate Planning',
    status: 'open',
    risk_score: 22,
    risk_category: 'none',
    budget: 800000,
    billing_model: 'flat_fee',
    created_at: '2024-02-05T10:00:00Z',
    updated_at: '2024-03-28T09:15:00Z',
    client_name: 'Fatima Al-Rashid',
    lawyer_name: 'Marcus Williams',
    last_activity: '2024-03-28T09:15:00Z',
  },
  {
    id: 'case-3',
    firm_id: 'firm-1',
    title: 'Rodriguez Immigration Appeal',
    practice_area: 'Immigration',
    status: 'pre_filing',
    risk_score: 55,
    risk_category: 'unanswered',
    budget: 350000,
    billing_model: 'flat_fee',
    created_at: '2024-02-20T11:00:00Z',
    updated_at: '2024-03-22T16:00:00Z',
    client_name: 'Carlos Rodriguez',
    lawyer_name: 'Sarah Chen',
    last_activity: '2024-03-22T16:00:00Z',
  },
  {
    id: 'case-4',
    firm_id: 'firm-1',
    title: 'Novak Divorce Proceedings',
    practice_area: 'Family Law',
    status: 'in_court',
    risk_score: 85,
    risk_category: 'inactivity',
    budget: 600000,
    billing_model: 'hourly',
    created_at: '2023-11-01T08:00:00Z',
    updated_at: '2024-03-08T11:00:00Z',
    client_name: 'Elena Novak',
    lawyer_name: 'James Park',
    last_activity: '2024-03-08T11:00:00Z',
  },
  {
    id: 'case-5',
    firm_id: 'firm-1',
    title: 'Chen IP Portfolio Defense',
    practice_area: 'Intellectual Property',
    status: 'open',
    risk_score: 18,
    risk_category: 'none',
    budget: 2000000,
    billing_model: 'hourly',
    created_at: '2024-03-01T09:00:00Z',
    updated_at: '2024-03-29T10:00:00Z',
    client_name: 'TechNova Inc.',
    lawyer_name: 'Sarah Chen',
    last_activity: '2024-03-29T10:00:00Z',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    case_id: 'case-1',
    title: 'Draft motion to compel discovery',
    description: 'Prepare comprehensive motion addressing Meridian\'s failure to produce documents',
    status: 'in_progress',
    assignee_id: 'user-1',
    assignee_name: 'Sarah Chen',
    due_date: '2024-04-05T17:00:00Z',
    created_at: '2024-03-20T09:00:00Z',
  },
  {
    id: 'task-2',
    case_id: 'case-1',
    title: 'Review deposition transcripts',
    status: 'done',
    assignee_id: 'user-1',
    assignee_name: 'Sarah Chen',
    due_date: '2024-03-25T17:00:00Z',
    created_at: '2024-03-15T09:00:00Z',
  },
  {
    id: 'task-3',
    case_id: 'case-3',
    title: 'Prepare Form I-485 supplemental brief',
    status: 'not_started',
    assignee_id: 'user-1',
    assignee_name: 'Sarah Chen',
    due_date: '2024-04-10T17:00:00Z',
    created_at: '2024-03-22T09:00:00Z',
  },
  {
    id: 'task-4',
    case_id: 'case-5',
    title: 'File trademark opposition response',
    status: 'in_progress',
    assignee_id: 'user-1',
    assignee_name: 'Sarah Chen',
    due_date: '2024-04-02T17:00:00Z',
    created_at: '2024-03-28T09:00:00Z',
  },
];

export const mockAlerts: AIAlert[] = [
  {
    id: 'alert-1',
    case_id: 'case-4',
    case_title: 'Novak Divorce Proceedings',
    type: 'inactivity',
    risk_level: 'high',
    description: 'No meaningful case activity recorded in 21 days. Court date approaching in 14 days. Immediate review recommended.',
    resolved: false,
    created_at: '2024-03-29T08:00:00Z',
  },
  {
    id: 'alert-2',
    case_id: 'case-1',
    case_title: 'Harrison v. Meridian Corp.',
    type: 'missed_deadline',
    risk_level: 'high',
    description: 'Internal review deadline passed 3 days ago without task completion. Discovery motion still in draft.',
    resolved: false,
    created_at: '2024-03-29T07:00:00Z',
  },
  {
    id: 'alert-3',
    case_id: 'case-3',
    case_title: 'Rodriguez Immigration Appeal',
    type: 'unanswered_message',
    risk_level: 'medium',
    description: 'Client message unanswered for 96+ hours. Client last contacted on March 25th regarding document submission.',
    resolved: false,
    created_at: '2024-03-29T06:30:00Z',
  },
  {
    id: 'alert-4',
    case_id: 'case-2',
    case_title: 'Al-Rashid Family Trust',
    type: 'inactivity',
    risk_level: 'low',
    description: 'No document uploads in 14 days. Case is in active review phase — confirm status with assigned attorney.',
    resolved: true,
    resolved_by: 'Marcus Williams',
    resolved_at: '2024-03-28T16:00:00Z',
    created_at: '2024-03-28T08:00:00Z',
  },
];

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    case_id: 'case-1',
    case_title: 'Harrison v. Meridian Corp.',
    dms_document_id: 's3://lexora/case-1/complaint.pdf',
    file_name: 'Amended_Complaint_v3.pdf',
    doc_type: 'pleading',
    is_public_to_client: true,
    uploaded_by: 'user-1',
    uploaded_by_name: 'Sarah Chen',
    uploaded_at: '2024-03-15T10:00:00Z',
    file_size: 2456789,
  },
  {
    id: 'doc-2',
    case_id: 'case-1',
    case_title: 'Harrison v. Meridian Corp.',
    dms_document_id: 's3://lexora/case-1/discovery.pdf',
    file_name: 'Discovery_Request_Set1.pdf',
    doc_type: 'pleading',
    is_public_to_client: false,
    uploaded_by: 'user-1',
    uploaded_by_name: 'Sarah Chen',
    uploaded_at: '2024-03-20T14:00:00Z',
    file_size: 890123,
  },
  {
    id: 'doc-3',
    case_id: 'case-2',
    case_title: 'Al-Rashid Family Trust',
    dms_document_id: 's3://lexora/case-2/trust.pdf',
    file_name: 'Trust_Agreement_Draft_v2.pdf',
    doc_type: 'contract',
    is_public_to_client: true,
    uploaded_by: 'user-2',
    uploaded_by_name: 'Marcus Williams',
    uploaded_at: '2024-03-25T11:00:00Z',
    file_size: 1234567,
  },
  {
    id: 'doc-4',
    case_id: 'case-3',
    case_title: 'Rodriguez Immigration Appeal',
    dms_document_id: 's3://lexora/case-3/brief.pdf',
    file_name: 'Appeal_Brief_Draft.pdf',
    doc_type: 'draft',
    is_public_to_client: false,
    uploaded_by: 'user-1',
    uploaded_by_name: 'Sarah Chen',
    uploaded_at: '2024-03-22T09:00:00Z',
    file_size: 567890,
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    case_id: 'case-3',
    case_title: 'Rodriguez Immigration Appeal',
    sender_id: 'client-3',
    sender_name: 'Carlos Rodriguez',
    sender_role: 'client',
    receiver_id: 'user-1',
    receiver_name: 'Sarah Chen',
    content: 'Hi Sarah, I wanted to follow up on the status of my appeal brief. I submitted all the additional documents you requested last week. When can I expect to hear back about the next steps?',
    is_client_visible: true,
    status: 'seen',
    seen_at: '2024-03-25T10:00:00Z',
    created_at: '2024-03-25T09:30:00Z',
  },
  {
    id: 'msg-2',
    case_id: 'case-1',
    case_title: 'Harrison v. Meridian Corp.',
    sender_id: 'client-1',
    sender_name: 'James Harrison',
    sender_role: 'client',
    receiver_id: 'user-1',
    receiver_name: 'Sarah Chen',
    content: 'Sarah, I\'m concerned about the upcoming court date on April 15th. Do we have everything we need? I\'d like to schedule a call this week.',
    is_client_visible: true,
    status: 'sent',
    created_at: '2024-03-28T15:00:00Z',
  },
  {
    id: 'msg-3',
    case_id: 'case-1',
    case_title: 'Harrison v. Meridian Corp.',
    sender_id: 'user-1',
    sender_name: 'Sarah Chen',
    sender_role: 'lawyer',
    receiver_id: 'user-2',
    receiver_name: 'Marcus Williams',
    content: 'Marcus — can you review the deposition summaries before EOD? Need your sign-off before I send to client.',
    is_client_visible: false,
    status: 'seen',
    is_internal_note: true,
    created_at: '2024-03-28T11:00:00Z',
  },
];

export const mockTimeEntries: TimeEntry[] = [
  {
    id: 'te-1',
    case_id: 'case-1',
    case_title: 'Harrison v. Meridian Corp.',
    lawyer_id: 'user-1',
    lawyer_name: 'Sarah Chen',
    started_at: '2024-03-28T09:00:00Z',
    ended_at: '2024-03-28T11:30:00Z',
    duration_minutes: 150,
    description: 'Drafting motion to compel; reviewed Meridian document production log',
    is_billed: true,
  },
  {
    id: 'te-2',
    case_id: 'case-1',
    case_title: 'Harrison v. Meridian Corp.',
    lawyer_id: 'user-1',
    lawyer_name: 'Sarah Chen',
    started_at: '2024-03-27T14:00:00Z',
    ended_at: '2024-03-27T16:00:00Z',
    duration_minutes: 120,
    description: 'Client call - case strategy discussion re: trial prep',
    is_billed: true,
  },
  {
    id: 'te-3',
    case_id: 'case-3',
    case_title: 'Rodriguez Immigration Appeal',
    lawyer_id: 'user-1',
    lawyer_name: 'Sarah Chen',
    started_at: '2024-03-26T10:00:00Z',
    ended_at: '2024-03-26T12:30:00Z',
    duration_minutes: 150,
    description: 'Research on recent USCIS precedent decisions for I-485 appeals',
    is_billed: false,
  },
];

export const mockEvents: CaseEvent[] = [
  {
    id: 'ev-1',
    case_id: 'case-1',
    actor_id: 'user-1',
    actor_name: 'Sarah Chen',
    actor_role: 'lawyer',
    type: 'ai_alert_generated',
    metadata: { alert_type: 'missed_deadline', risk_level: 'high' },
    created_at: '2024-03-29T08:00:00Z',
  },
  {
    id: 'ev-2',
    case_id: 'case-1',
    actor_id: 'user-1',
    actor_name: 'Sarah Chen',
    actor_role: 'lawyer',
    type: 'document_uploaded',
    metadata: { file_name: 'Amended_Complaint_v3.pdf' },
    created_at: '2024-03-28T14:30:00Z',
  },
  {
    id: 'ev-3',
    case_id: 'case-1',
    actor_id: 'client-1',
    actor_name: 'James Harrison',
    actor_role: 'client',
    type: 'message_sent',
    metadata: { preview: 'I\'m concerned about the upcoming court date...' },
    created_at: '2024-03-28T15:00:00Z',
  },
  {
    id: 'ev-4',
    case_id: 'case-1',
    actor_id: 'user-1',
    actor_name: 'Sarah Chen',
    actor_role: 'lawyer',
    type: 'task_updated',
    metadata: { task: 'Review deposition transcripts', new_status: 'done' },
    created_at: '2024-03-25T16:00:00Z',
  },
  {
    id: 'ev-5',
    case_id: 'case-1',
    actor_id: 'user-1',
    actor_name: 'Sarah Chen',
    actor_role: 'lawyer',
    type: 'case_created',
    metadata: {},
    created_at: '2024-01-10T09:00:00Z',
  },
];
